//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public string MAKH { get; set; }
        public string TENKH { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> SDT { get; set; }
        public string MATKHAU { get; set; }
        public string DIACHI { get; set; }
        public string GIOITINH { get; set; }
    }
}
