//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public SACH()
        {
            this.GIOHANGs = new HashSet<GIOHANG>();
        }
    
        public string MASACH { get; set; }
        public string TENSACH { get; set; }
        public string MATG { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public string HINHANH { get; set; }
        public Nullable<System.DateTime> NGAYXUATBAN { get; set; }
        public string MANXB { get; set; }
        public string MALOAI { get; set; }
        public string MOTA { get; set; }
    
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        public virtual LOAISACH LOAISACH { get; set; }
        public virtual NXB NXB { get; set; }
        public virtual TACGIA TACGIA { get; set; }
    }
}
